import { describe, it, expect } from "vitest";
import { isValidEmail, isValidUuid, isValidSlug, isValidTypeformFormId } from "@/lib/validators";

describe("isValidEmail", () => {
  it("accepts standard corporate emails", () => {
    expect(isValidEmail("user@vtex.com")).toBe(true);
    expect(isValidEmail("john.doe+tag@example.co.uk")).toBe(true);
    expect(isValidEmail("vendor@company.com.br")).toBe(true);
  });

  it("rejects emails missing @", () => {
    expect(isValidEmail("userATdomain.com")).toBe(false);
    expect(isValidEmail("notanemail")).toBe(false);
  });

  it("rejects emails missing domain part", () => {
    expect(isValidEmail("user@")).toBe(false);
    expect(isValidEmail("@domain.com")).toBe(false);
  });

  it("rejects emails with spaces", () => {
    expect(isValidEmail("user @domain.com")).toBe(false);
    expect(isValidEmail("us er@domain.com")).toBe(false);
  });

  it("rejects emails with missing TLD", () => {
    expect(isValidEmail("user@domain")).toBe(false);
    expect(isValidEmail("user@domain.")).toBe(false);
  });

  it("rejects empty string", () => {
    expect(isValidEmail("")).toBe(false);
  });

  it("rejects values with multiple @ signs", () => {
    expect(isValidEmail("user@@domain.com")).toBe(false);
  });
});

describe("isValidUuid", () => {
  it("accepts a valid UUID v4", () => {
    expect(isValidUuid("550e8400-e29b-41d4-a716-446655440000")).toBe(true);
    expect(isValidUuid("123e4567-e89b-12d3-a456-426614174000")).toBe(true);
  });

  it("is case-insensitive", () => {
    expect(isValidUuid("550E8400-E29B-41D4-A716-446655440000")).toBe(true);
  });

  it("rejects UUIDs with wrong segment lengths", () => {
    expect(isValidUuid("550e8400-e29b-41d4-a716-44665544000")).toBe(false);
    expect(isValidUuid("550e8400e29b41d4a716446655440000")).toBe(false);
  });

  it("rejects non-UUID strings", () => {
    expect(isValidUuid("not-a-uuid")).toBe(false);
    expect(isValidUuid("")).toBe(false);
    expect(isValidUuid("12345")).toBe(false);
  });

  it("rejects UUIDs with invalid characters", () => {
    expect(isValidUuid("550e8400-e29b-41d4-a716-44665544000g")).toBe(false);
  });
});

describe("isValidSlug", () => {
  it("accepts valid slugs generated by slugify()", () => {
    expect(isValidSlug("acme-corp")).toBe(true);
    expect(isValidSlug("vendor123")).toBe(true);
    expect(isValidSlug("a")).toBe(true);
    expect(isValidSlug("my-vendor-name-2024")).toBe(true);
  });

  it("rejects slugs with uppercase letters", () => {
    expect(isValidSlug("Acme-Corp")).toBe(false);
    expect(isValidSlug("VENDOR")).toBe(false);
  });

  it("rejects slugs with leading or trailing hyphens", () => {
    expect(isValidSlug("-acme")).toBe(false);
    expect(isValidSlug("acme-")).toBe(false);
  });

  it("rejects path traversal patterns", () => {
    expect(isValidSlug("../etc/passwd")).toBe(false);
    expect(isValidSlug("../../secret")).toBe(false);
    expect(isValidSlug("vendor/name")).toBe(false);
  });

  it("rejects slugs with special characters", () => {
    expect(isValidSlug("acme@corp")).toBe(false);
    expect(isValidSlug("acme corp")).toBe(false);
    expect(isValidSlug("acme.corp")).toBe(false);
  });

  it("rejects slugs longer than 100 characters", () => {
    expect(isValidSlug("a".repeat(101))).toBe(false);
    expect(isValidSlug("a".repeat(100))).toBe(true);
  });

  it("rejects empty string", () => {
    expect(isValidSlug("")).toBe(false);
  });
});

describe("isValidTypeformFormId", () => {
  it("accepts typical Typeform form IDs", () => {
    expect(isValidTypeformFormId("ABC123xyz")).toBe(true);
    expect(isValidTypeformFormId("abc123")).toBe(true);
    expect(isValidTypeformFormId("form-id_v2")).toBe(true);
  });

  it("rejects IDs shorter than 3 characters", () => {
    expect(isValidTypeformFormId("ab")).toBe(false);
    expect(isValidTypeformFormId("a")).toBe(false);
  });

  it("rejects IDs longer than 64 characters", () => {
    expect(isValidTypeformFormId("a".repeat(65))).toBe(false);
    expect(isValidTypeformFormId("a".repeat(64))).toBe(true);
  });

  it("rejects IDs with special characters", () => {
    expect(isValidTypeformFormId("form id")).toBe(false);
    expect(isValidTypeformFormId("form@id")).toBe(false);
    expect(isValidTypeformFormId("form/id")).toBe(false);
  });

  it("rejects empty string", () => {
    expect(isValidTypeformFormId("")).toBe(false);
  });
});
